---
# tasks file for mk-ovpn-gen

#USAGE:
# ./mkvpn.yml -i localhost, -e 'cadays= 1200 country="ES" province="BCN" \ 
#  city="Sant Cugat" org="SabuesoORG" email="ramiro@gnubit.com" ou="SabuesoOU"'

#- debug: 
#   msg: copy EASY-RSA if exists under /usr/share if exists

#Check path
- name: Ansible check file exists example.
  stat:
    path: /usr/share/easy-rsa/
  register: usr_easyrsa

#Check openssl version
- name: Checking Openssl version
  shell: openssl version |grep -o -E '[0-9]\.[0-9]\.[0-9]'
  register: openssl_output

#Copy if easy-rsa exists
- synchronize:
    src: /usr/share/easy-rsa
    dest: cert_files
    rsync_opts:    
      - "--exclude=keys"
      #some times, the "keys" dir unthe easy-rsa is not wide readeable
  when: usr_easyrsa.stat.exists

#Workaround https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905854
- name: "Testing and patching easy-rsa & openssl bug for Debian9"
  file: 
    src: '{{ playbook_dir }}/cert_files/easy-rsa/openssl-1.0.0.cnf'
    dest: '{{ playbook_dir }}/cert_files/easy-rsa/openssl.cnf'
    state: link
  when: openssl_output.stdout > '1.0.0'

#CA part
- name: "Clean & Init CA cert"
  shell: "source vars && ./clean-all && ./pkitool --initca"
  args:
     executable: /bin/bash
     chdir: '{{ playbook_dir }}/cert_files/easy-rsa/'
#  register: source_output
#- debug: var=source_output.stdout_lines

#Massive regexp in the easy-rsa's vars file
- lineinfile:
    path: '{{ playbook_dir }}/cert_files/easy-rsa/vars'
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'export CA_EXPIRE=.*$', line: 'export CA_EXPIRE={{ cadays }}' }
    - { regexp: 'export KEY_COUNTRY=.*$', line: 'export KEY_COUNTRY="{{ country }}"' }
    - { regexp: 'export KEY_PROVINCE=.*$', line: 'export KEY_PROVINCE="{{ province }}"' }
    - { regexp: 'export KEY_CITY=.*$', line: 'export KEY_CITY="{{ city }}"' }
    - { regexp: 'export KEY_ORG=.*$', line: 'export KEY_ORG="{{ org }}"' }
    - { regexp: 'export KEY_EMAIL=.*$', line: 'export KEY_EMAIL="{{ email }}"' }
    - { regexp: 'export KEY_OU=.*$', line: 'export KEY_OU="{{ ou}}"' }

#Appliance part
- name: "Mikrotik's device cert"
  shell: "source vars && ./pkitool --server {{ devicecert }} "
  args:
     executable: /bin/bash
     chdir: '{{ playbook_dir }}/cert_files/easy-rsa/'

- name: "Convert appliance private key to .pem format"
  shell: "openssl rsa -in keys/{{ devicecert }}.key -out keys/{{ devicecert }}.pem"
  args:
     executable: /bin/bash
     chdir: '{{ playbook_dir }}/cert_files/easy-rsa/'